fix: Add missing queries to fusion input adapter
cyberbit/telem pull request #74
Opened 2024-08-16 03:58 UTC by bananasov

Added water, tritium, deuterium and DT Fuel

I wanted to look at fission and the rest from #73 but apparently they aren't missing those inputs, fusion did though

2024-08-16 12:37 UTC, bananasov commented
Apparently, evaporation towers are missing input and outputs too

2024-08-16 14:26 UTC, cyberbit commented on src/telem/lib/input/mekanism/FusionReactorInputAdapter.lua
> +            tritium                     = fn():call('getTrititum'):div(1000):fluid(),
Not sure if it is a typo in the mod or here, but I will check in-game later on if `getTrititum` is right. Wouldn't be the first time something like that is real.

2024-08-17 01:27 UTC, cyberbit commented on src/telem/lib/input/mekanism/FusionReactorInputAdapter.lua
> +            tritium                     = fn():call('getTrititum'):div(1000):fluid(),
Looks like it is `getTritium`:

![image](https://github.com/user-attachments/assets/df75cb16-f1c1-4269-874a-db8ad4f398b6)

2024-08-17 01:43 UTC, cyberbit requested changes
Looks good, if you can fix typo and the `amount` things on the additions I will merge!

2024-08-17 01:43 UTC, cyberbit commented on src/telem/lib/input/mekanism/FusionReactorInputAdapter.lua
> +            water                       = fn():call('getWater'):div(1000):fluid(),
These need to be modified to pull `amount` from the result of the call before calculating. See example from other adapters below:

https://github.com/cyberbit/telem/blob/f7e54a8d6cb496040cb7d15f99a7a0231a409fab/src/telem/lib/input/mekanism/PressurizedReactionChamberInputAdapter.lua#L19

2024-08-17 01:43 UTC, cyberbit commented on src/telem/lib/input/mekanism/FusionReactorInputAdapter.lua
> +            tritium                     = fn():call('getTrititum'):div(1000):fluid(),
The call has a typo, should be `getTritium`

2024-08-17 21:25 UTC, cyberbit approved these changes

2024-08-17 21:29 UTC, merged